version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.EC2
    versions:
    - 3.5.29.3
    - 3.5.29.4
    - 3.5.30
    - 3.5.31.1
    - 3.5.31.2
    - 3.5.31.3
    - 3.5.31.4
    - 3.5.31.5
    - 3.5.31.6
    - 3.5.31.7
    - 3.5.31.8
    - 3.5.31.9
    - 3.5.32
    - 3.5.32.1
    - 3.5.32.2
    - 3.5.32.3
    - 3.5.33
    - 3.5.34
    - 3.5.35
    - 3.5.35.1
    - 3.7.0.1
    - 3.7.0.2
    - 3.7.1
    - 3.7.1.1
    - 3.7.2
    - 3.7.2.1
    - 3.7.3
    - 3.7.3.1
    - 3.7.3.2
    - 3.7.4
    - 3.7.4.1
    - 3.7.4.3
    - 3.7.4.4
    - 3.7.4.5
    - 3.7.5
  - dependency-name: aliyun-net-sdk-ecs
    versions:
    - 4.23.10
    - 4.23.11
    - 4.23.7
    - 4.23.9
  - dependency-name: Microsoft.EntityFrameworkCore.Design
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.ML
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: Moq
    versions:
    - 4.16.0
