// <auto-generated />
using EFConsoleDemo.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace EFConsoleDemo.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20171031103414_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("EFConsoleDemo.Model.Author", b =>
                {
                    b.Property<int>("AuthorId");

                    b.Property<int>("Age");

                    b.Property<string>("Name");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("EFConsoleDemo.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthorId");

                    b.Property<string>("BookName");

                    b.Property<double>("Price");

                    b.Property<string>("Publisher");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EFConsoleDemo.Model.Author", b =>
                {
                    b.HasOne("EFConsoleDemo.Model.Book", "Books")
                        .WithOne("Authors")
                        .HasForeignKey("EFConsoleDemo.Model.Author", "AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
